ARG image_tag=latest
ARG node_version
FROM elifesciences/journal_composer:${image_tag} AS composer
FROM elifesciences/journal_npm:${image_tag} as npm
FROM node:${node_version}

RUN sed -i -e 's|^# \(deb http://snapshot.debian.org.*\)|\1|' -e 's|^deb http://deb.debian.org.*|# &|' /etc/apt/sources.list
RUN apt-get update -o Acquire::Check-Valid-Until=false && apt-get install --no-install-recommends -y \
    libvips \
    && rm -rf /var/lib/apt/lists/*

COPY --from=npm /app/node_modules/ node_modules/

COPY assets/images/ assets/images/
COPY gulpfile.js ./
COPY --from=composer /app/vendor/elife/patterns/resources/assets/ vendor/elife/patterns/resources/assets/

RUN node_modules/.bin/gulp assets
