ARG image_tag=latest
FROM elifesciences/journal:${image_tag} AS fpm
FROM nginx:1.13.12-alpine

COPY .docker/nginx-default.conf /etc/nginx/conf.d/default.conf
COPY --from=fpm /srv/journal/web/ /srv/journal/web/
