ARG image_tag=latest
ARG node_version
FROM elifesciences/journal_composer:${image_tag} AS composer
FROM elifesciences/journal_npm:${image_tag} as npm
FROM node:${node_version}

RUN sed -i -E '$!N; s|^# (http://snapshot\.debian\.org/\S*)\nURIs: http://deb\.debian\.org/\S*|URIs: \1|; P; D' /etc/apt/sources.list.d/debian.sources
RUN apt-get update -o Acquire::Check-Valid-Until=false && apt-get install --no-install-recommends -y \
    libvips \
    && rm -rf /var/lib/apt/lists/*

COPY --from=npm /app/node_modules/ node_modules/

COPY assets/images/ assets/images/
COPY gulpfile.js ./
COPY --from=composer /app/vendor/elife/patterns/resources/assets/ vendor/elife/patterns/resources/assets/

RUN node_modules/.bin/gulp assets
