ARG node_version
FROM node:${node_version} as npm

RUN apt-get update && apt-get install --no-install-recommends -y \
    nasm \
    libvips-dev \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /usr/app

COPY npm-shrinkwrap.json \
    package.json \
    /usr/app/
RUN npm install
