ARG image_tag=latest
FROM elifesciences/journal_composer:${image_tag} as composer
FROM elifesciences/journal_npm:${image_tag} as npm
FROM node:6.14.1

COPY --from=npm /node_modules/ node_modules/

COPY assets/images/ assets/images/
COPY critical-css.json \
    gulpfile.js \
    ./
COPY --from=composer /app/vendor/elife/patterns/resources/assets/ vendor/elife/patterns/resources/assets/

RUN node_modules/.bin/gulp assets

COPY --from=composer /app/web/bundles/ /web/bundles/
