ARG image_tag=latest
FROM elifesciences/journal_assets:${image_tag} AS assets
FROM nginx:1.13.12-alpine

COPY .docker/nginx-default.conf /etc/nginx/conf.d/default.conf
COPY --from=assets /web/ /srv/journal/web/
