ARG node_version
FROM node:${node_version} as npm

RUN sed -i -e 's|^# \(deb http://snapshot.debian.org.*\)|\1|' -e 's|^deb http://deb.debian.org.*|# &|' /etc/apt/sources.list
RUN apt-get update -o Acquire::Check-Valid-Until=false && apt-get install --no-install-recommends -y \
    nasm \
    libvips-dev \
    && wget http://archive.debian.org/debian/pool/main/p/phantomjs/phantomjs_2.1.1+dfsg-2_$(dpkg --print-architecture).deb \
    && apt-get install -y ./phantomjs_2.1.1+dfsg-2_$(dpkg --print-architecture).deb \
    && rm ./phantomjs_2.1.1+dfsg-2_$(dpkg --print-architecture).deb \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app

# Fix for ARM64
ENV CFLAGS="-DPNG_ARM_NEON_OPT=0"
COPY npm-shrinkwrap.json \
    package.json \
    /app/
RUN npm install
