version: '3'

services:
    composer:
        build:
            args:
                composer_dev_arg:
        volumes:
            - ./composer.json:/app/composer.json
            - ./composer.lock:/app/composer.lock
            - ./vendor:/app/vendor
    npm:
        volumes:
            - ./npm-shrinkwrap.json:/npm-shrinkwrap.json
            - ./package.json:/package.json
            - node_modules:/node_modules
    assets_builder:
        volumes:
            #
#            - ../patterns-php/resources/assets:/vendor/elife/patterns/resources/assets

            - ./assets/images:/assets/images
            - assets:/web
            - build:/build
            - node_modules:/node_modules
            - ./gulpfile.js:/gulpfile.js
    app:
        # Comment out the build section if you don't want to run the xdebug Dockerfile
        build:
            context: .
            dockerfile: Dockerfile.xdebug
            args:
                image_tag: ${IMAGE_TAG}
                php_version: ${PHP_VERSION}
        environment:
            - APP_ENV=${APP_ENV}
            - XDEBUG_MODE=debug
            - XDEBUG_CONFIG=client_host=host.docker.internal
            - PHP_IDE_CONFIG=serverName=DockerApp
        volumes:
            - ./:/srv/journal
            - ./.docker/php.ini:/usr/local/etc/php/conf.d/x-dev.ini
            - /srv/journal/vendor
            - /srv/journal/var
            - build:/srv/journal/build
            - critical_css:/srv/journal/build/critical-css

            - ../api-sdk-php:/srv/journal/vendor/elife/api-sdk
            - ../patterns-php:/srv/journal/vendor/elife/patterns
    web:
        volumes:
            - assets:/srv/journal/web
    api_dummy:
        #        image: ghcr.io/elifesciences/api-dummy:${DEPENDENCIES_API_DUMMY}
        build:
            context: ../api-dummy
        ports:
            - '${JOURNAL_API_DUMMY_PORT}:8080'
        platform: linux/arm64
        stop_grace_period: 1s
    critical_css:
        volumes:
            - critical_css:/build/critical-css
            - node_modules:/node_modules

volumes:
    assets:
    build:
    critical_css:
    node_modules:
