ARG node_version
FROM node:16.17.0-bullseye as npm

RUN apt-get update && apt-get install --no-install-recommends -y \
    nasm \
    libvips-dev \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /usr/app

COPY npm-shrinkwrap.json \
    package.json \
    /usr/app
RUN npm install
