when@dev: &web_profiler_routes
    web_profiler_wdt:
        resource: '@WebProfilerBundle/Resources/config/routing/wdt.php'
        prefix: /_wdt

    web_profiler_profiler:
        resource: '@WebProfilerBundle/Resources/config/routing/profiler.php'
        prefix: /_profiler

# WebProfilerBundle is also active in "ci" (config/bundles.php)
when@ci: *web_profiler_routes