imports:
  - resource: config_prod.yml

parameters:
    api_connect_timeout: 1
    api_timeout: 2
    api_connect_timeout_slow: 2
    api_timeout_slow: 6

csa_guzzle:
    profiler:
        enabled: true
    clients:
        elife_api_boostings:
            config:
                base_uri: https://boostings--search.elifesciences.org
