imports:
  - resource: config.yml

parameters:
    api_url_boostings: https://boostings--search.elifesciences.org

csa_guzzle:
    profiler:
        enabled: true

framework:
    profiler: ~
    router:
        resource: '%kernel.project_dir%/app/config/routing_dev.yml'

monolog:
    handlers:
        console:
            channels:
              - '!event'
            type: console
            formatter: monolog.formatter.line
        main:
            channels:
              - '!event'
            level: debug
            path: 'php://stderr'
            type: stream

swiftmailer:
    disable_delivery: true

web_profiler:
    toolbar: true
