imports:
  - resource: config.yml

csa_guzzle:
    profiler:
        enabled: true

framework:
    profiler: ~
    router:
        resource: '%kernel.root_dir%/config/routing_dev.yml'

monolog:
    handlers:
        console:
            channels:
              - !event
            type: console
            formatter: monolog.formatter.line
        main:
            channels:
              - !event
            level: debug
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            type: stream
            formatter: monolog.formatter.line

swiftmailer:
    disable_delivery: true

web_profiler:
    toolbar: true
