services:

    _defaults:
        public: true

    elife.api_validator.validator:
        class: eLife\ApiValidator\MessageValidator\JsonMessageValidator
        arguments:
          - '@elife.api_validator.schema_finder'
          - '@elife.api_validator.schema_validator'
        tags:
          - name: optional

    elife.api_validator.validator.fake_https:
        class: eLife\ApiValidator\MessageValidator\FakeHttpsMessageValidator
        decorates: elife.api_validator.validator
        arguments:
          - '@elife.api_validator.validator.fake_https.inner'
        tags:
          - name: optional

    elife.api_validator.schema_validator:
        class: JsonSchema\Validator
        public: false
        tags:
          - name: optional

    elife.api_validator.schema_finder:
        class: eLife\ApiValidator\SchemaFinder\PathBasedSchemaFinder
        public: false
        arguments:
          - '@=composer_locate("elife/api")~"/dist/model"'
        tags:
          - name: optional

    framework.http_client.clients.elife_api:
        class: test\eLife\Journal\MockApiHttpClient
        arguments:
          - '%api_mock%'
          - '%api_url%'
          - ['authorization', 'content-length', 'host', 'referer', 'user-agent']
          - '@?elife.api_validator.validator'

    framework.http_client.clients.elife_api_search_page:
        class: test\eLife\Journal\MockApiHttpClient
        arguments:
          - '%api_mock%'
          - '%api_url_search_page%'
          - ['authorization', 'content-length', 'host', 'referer', 'user-agent']
          - '@?elife.api_validator.validator'

    framework.http_client.clients.streamer:
        class: test\eLife\Journal\MockApiHttpClient
        arguments:
          - '%api_mock%'
          - ''
          - ['accept', 'authorization', 'cache-control', 'content-length', 'host', 'if-modified-since', 'if-none-match', 'referer', 'user-agent', 'x-forwarded-for', 'x-forwarded-host', 'x-forwarded-port', 'x-forwarded-proto']

    framework.http_client.clients.oauth:
        class: test\eLife\Journal\MockApiHttpClient
        arguments:
          - '%api_mock%'
          - ''
          - ['authorization', 'content-length', 'host', 'referer', 'user-agent']

