services:

    elife.api_sdk.client:
        class: eLife\ApiSdk\HttpClient\Guzzle6HttpClient
        arguments:
          - '@csa_guzzle.client.elife_api'

    elife.api_sdk.client.warning_checking:
        class: eLife\ApiSdk\HttpClient\WarningCheckingHttpClient
        decorates: elife.api_sdk.client
        arguments:
          - '@elife.api_sdk.client.warning_checking.inner'
          - '@logger'

    elife.api_sdk.blog:
        class: eLife\ApiSdk\ApiClient\BlogClient
        arguments:
          - '@elife.api_sdk.client'

    elife.api_sdk.collections:
        class: eLife\ApiSdk\ApiClient\CollectionsClient
        arguments:
          - '@elife.api_sdk.client'

    elife.api_sdk.labs:
        class: eLife\ApiSdk\ApiClient\LabsClient
        arguments:
          - '@elife.api_sdk.client'

    elife.api_sdk.podcast:
        class: eLife\ApiSdk\ApiClient\PodcastClient
        arguments:
          - '@elife.api_sdk.client'

    elife.api_sdk.search:
        class: eLife\ApiSdk\ApiClient\SearchClient
        arguments:
          - '@elife.api_sdk.client'

    elife.api_sdk.subjects:
        class: eLife\ApiSdk\ApiClient\SubjectsClient
        arguments:
          - '@elife.api_sdk.client'

    elife.journal.templating.promise_aware:
        class: eLife\Journal\Templating\PromiseAwareEngine
        decorates: templating
        arguments:
          - '@elife.journal.templating.promise_aware.inner'

    elife.journal.twig.extension.assets:
        class: eLife\Journal\Twig\AssetsExtension
        arguments:
          - '@elife.patterns.pattern_renderer.asset_recording'
        tags:
          - name: twig.extension

    elife.journal.twig.extension.info_bar:
        class: eLife\Journal\Twig\InfoBarExtension
        arguments:
          - '@elife.patterns.pattern_renderer'
        tags:
          - name: twig.extension

    elife.journal.twig.extension.pattern:
        class: eLife\Journal\Twig\PatternExtension
        arguments:
          - '@elife.patterns.pattern_renderer'
        tags:
          - name: twig.extension

    elife.journal.view_model.factory.footer:
        class: eLife\Journal\ViewModel\FooterFactory
        arguments:
          - '@elife.api_sdk.subjects'
          - '@router'
          - '@puli.url_generator'

    elife.journal.view_model.factory.listing_teaser:
        class: eLife\Journal\ViewModel\ListingTeaserFactory
        arguments:
          - '@router'
          - '@puli.url_generator'
          - '@elife.api_sdk.subjects'

    elife.journal.view_model.factory.listing_teaser_secondary:
        class: eLife\Journal\ViewModel\SecondaryListingTeaserFactory
        arguments:
          - '@router'
          - '@elife.api_sdk.subjects'

    elife.journal.view_model.factory.site_header:
        class: eLife\Journal\ViewModel\SiteHeaderFactory
        arguments:
          - '@router'
          - '@puli.url_generator'

    elife.journal.view_model.factory.teaser_grid:
        class: eLife\Journal\ViewModel\TeaserGridFactory
        arguments:
          - '@router'

    elife.patterns.pattern_renderer:
        class: eLife\Patterns\PatternRenderer\MustachePatternRenderer
        arguments:
          - '@mustache'

    elife.patterns.pattern_renderer.asset_recording:
        class: eLife\Patterns\PatternRenderer\AssetRecordingPatternRenderer
        decorates: elife.patterns.pattern_renderer
        arguments:
          - '@elife.patterns.pattern_renderer.asset_recording.inner'

    elife.patterns.mustache.loader.puli:
        class: eLife\Patterns\Mustache\PuliLoader
        arguments:
          - '@puli.repository'

    elife.patterns.mustache.loader.filesystem:
        class: eLife\Patterns\Mustache\PatternLabLoader
        arguments:
          - '@=service("puli.repository").get("/elife/patterns/templates").getFilesystemPath()'

    phive.twig.deferred:
        class: Phive\Twig\Extensions\Deferred\DeferredExtension
        tags:
          - name: twig.extension
