services:

    elife.api_validator.validator:
        class: eLife\ApiValidator\MessageValidator\JsonMessageValidator
        public: false
        arguments:
          - '@elife.api_validator.schema_finder'
          - '@elife.api_validator.schema_validator'

    elife.api_validator.validator.fake_https:
        class: eLife\ApiValidator\MessageValidator\FakeHttpsMessageValidator
        decorates: elife.api_validator.validator
        arguments:
          - '@elife.api_validator.validator.fake_https.inner'

    elife.api_validator.schema_validator:
        class: JsonSchema\Validator
        public: false

    elife.api_validator.schema_finder:
        class: eLife\ApiValidator\SchemaFinder\PathBasedSchemaFinder
        public: false
        arguments:
          - '@=composer_locate("elife/api")~"/dist/model"'

    elife.guzzle.middleware.mock.storage:
        class: Csa\Bundle\GuzzleBundle\Cache\MockStorageAdapter
        arguments:
          - '%api_mock%'
          - ['Authorization', 'Content-Length', 'Host', 'host', 'Referer', 'referer', 'User-Agent', 'user-agent', 'X-Guzzle-Cache']

    elife.guzzle.middleware.mock.storage.validating:
        class: test\eLife\Journal\ValidatingStorageAdapter
        decorates: elife.guzzle.middleware.mock.storage
        arguments:
          - '@elife.guzzle.middleware.mock.storage.validating.inner'
          - '@elife.api_validator.validator'

    elife.guzzle.middleware.mock:
        class: Csa\Bundle\GuzzleBundle\GuzzleHttp\Middleware\MockMiddleware
        arguments:
          - '@elife.guzzle.middleware.mock.storage'
          - replay
        tags:
          - name: csa_guzzle.middleware
            alias: mock
            priority: -1501
