#!/usr/bin/env bash
set -e

rm -rf build/behat/
vendor/bin/behat --list-scenarios --tags '~wip' | vendor/bin/fastest --no-interaction --process 4 "JARNAIZ_JUNIT_OUTPUTDIR=build/behat JARNAIZ_JUNIT_FILENAME={n}.xml JOURNAL_INSTANCE=behat{p} vendor/bin/behat --strict --format junit {};"
