#!/usr/bin/env bash
set -e

rm -rf build/ci/behat/
vendor/bin/behat --list-scenarios --tags '~wip' | vendor/bin/fastest --no-interaction --process 8 "JARNAIZ_JUNIT_OUTPUTDIR=build/ci/behat JARNAIZ_JUNIT_FILENAME={n}.xml JOURNAL_INSTANCE=behat{p} vendor/bin/behat --strict --format junit {};"
