#!/usr/bin/env bash
set -e

rm -rf build/ci/phpunit/ && mkdir -p build/ci/phpunit
vendor/bin/fastest --no-interaction --process 4 --xml phpunit.xml.dist "JOURNAL_INSTANCE=phpunit{p} vendor/bin/phpunit --log-junit build/ci/phpunit/{n}.xml {};"
