#!/usr/bin/env bash
set -e

export FASTEST_OUTPUT_DIR=build/ci/phpunit
rm -rf "$FASTEST_OUTPUT_DIR" && mkdir -p "$FASTEST_OUTPUT_DIR"
php -dmemory_limit=-1 vendor/bin/phpunit --configuration phpunit.xml.dist --log-junit $FASTEST_OUTPUT_DIR/1.xml
