parameters:
    api_url: "%env(API_URL)%"
    api_url_search_page: "%env(API_URL_SEARCH_PAGE)%"
    api_url_public: "%env(API_URL_PUBLIC)%"
    api_connect_timeout: 2
    api_timeout: 5
    api_connect_timeout_slow: 3
    api_timeout_slow: 10
    mustache_stat_props: [ size, mtime ]
    honeypot_field: email_address
    side_by_side_view_url: https://lens.elifesciences.org/
    session_name: journal
    redis_cache: redis://redis/0
    redis_sessions: redis://redis/1
    submit_url: https://submit.elifesciences.org/
    submit_url_redirects:
        - .*\.elifesciences.org$
    crm_url: https://crm.elifesciences.org/crm/civicrm/
    crm_api_url: https://crm.elifesciences.org/crm/sites/all/modules/civicrm/extern/rest.php
    gtm_id: ~
    google_optimize_id: ~
    cb_id: ~
    trusted_hosts:
      - localhost
      - web
    status_checks:
        Articles: articles
    oauth2_client_id: some-id
    google_api_client.config:
        client_id: ~
        client_secret: ~
    google_api_client.refresh_token: ~
    google_api_client.optout_unsubscribe_spreadsheet_id: ~
    hypothesis_api: https://hypothes.is/api/
    hypothesis_authority: some-authority
    hypothesis_client_id: some-id
    xpub_client_id: some-id
    subject_rewrites: []
    dismissible_info_bars:
        aging:
            id: aging-special-issue
            text: '<a href="https://elifesciences.org/inside-elife/4f706531/special-issue-call-for-papers-in-aging-geroscience-and-longevity">Read the call for papers</a> for the eLife Special Issue on Aging, Geroscience and Longevity.'
            article_ids:
              - '26231'
    cache_control: private, no-cache, no-store, must-revalidate
    feature_xpub: true
    calls_to_action:
      - id: something-important
        path: ^(/$|/for-the-press)
        text: Here's something important
        button:
            text: Sign up for eLife news
            path: https://elifesciences.org/
        image:
            alt: ''
            uri: https://iiif.elifesciences.org/lax/09560%%2Felife-09560-fig1-v1.tif
            source:
                mediaType: image/jpg
                uri: https://iiif.elifesciences.org/lax/09560%%2Felife-09560-fig1-v1.tif/full/full/0/default.jpg
                filename: elife-09560-fig1-v1.jpg
            size:
                width: 4194
                height: 4714
        needsJs: false
