---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: journal
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: develop
  url: https://github.com/elifesciences/journal
